### ISSUE TITLE
"Empty" / Missing data UI Meta Issue

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#127]
This is a meta issue to list out places in the app where we need to define UI / behaviour for cases where some data is missing or empty:

- Define UI for popups / school detail page Volunteer Now button when school has no volunteering opportunities available (see some discussion on #123)

- UI for "empty" tabs - eg. when a school does not have any Finance or Nutrition info, what should the tab look like? Ideally, it would be the same template for any tab where there is no information available.

- UI for "empty" data inside compare modal. For eg. when: 1 school does not have Finance data, when both schools do not have finance data, etc.

**Comment by geohacker** [comment]
I think we have covered this pretty much everywhere. Closing.
