### ISSUE TITLE
Fix school image size lightbox on mobile

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#226]
It doesn't resize.

**Comment by batpad** [comment]
@imohkay looks great on mobile now -- its still a bit large and sometimes forces a scroll-bar on desktop, but much better than what it was. We can fine-tune if required, but I think this looks good. Thanks.

**Comment by batpad** [comment]
Btw - here's a page to test: http://dev.klp.org.in/school/37105/#?tab=info

**Comment by geohacker** [comment]
Tested, merged! Thanks @imohkay!

**Comment by imohkay** [comment]
@batpad reducing the image size should be easy. do you have a page example where there's a scrollbar on desktop? I can't find an example to replicate. It shouldn't happen, actually.

**Comment by batpad** [comment]
Here's what I was testing: http://dev.klp.org.in/school/37105/#?tab=info -- try the images there .. if it looks fine for you, don't bother. I'm getting vertical scroll, not horizontal ..

**Comment by imohkay** [comment]
@batpad cool i'll make the images smaller in general, but vertical scroll i'd rather not control beyond a point, tbh, if widths are constrained.

**Comment by batpad** [comment]
@imohkay that sounds great ..
