### ISSUE TITLE
Cleanup / refactor code for breadcrumbs

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#255]
My severe apologies - the current code to handle breadcrumbs is pretty terrible, but I wanted it to at least work for the release.

@iambibhas can you look into at least replacing the hard-coded URLs with some reverse() function, also, ideally, find a better way to do this. You can see the implementation here: https://github.com/klpdotorg/dubdubdub/commit/5c0fc22cf27a4420893dd14021af3ab0b21e4726

Not urgent, since it works, but please keep this in mind and refactor at some point, @iambibhas . My apologies, again.

**Comment by geohacker** [comment]
Won't fix.
