### ISSUE TITLE
Cannot close calendar on mobile

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#278]
Tapping the [x] has no effect. 
![2014-10-05 10 20 57](https://cloud.githubusercontent.com/assets/1021034/4517648/685d1246-4c4b-11e4-944e-8d233da60216.png)

**Comment by geohacker** [comment]
*Moving to Sprint 8*

**Comment by imohkay** [comment]
closing since I can't replicate on iOS and should be fixed in frontend refactor branch
