### ISSUE TITLE
Refactor common/renderers.py 

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#288]
This custom renderer to handle geometry=yes and output GeoJSON appropriately has gotten very messy since it tries to handle many special cases and is quite brittle. Need to think about this a bit and refactor.

**Comment by geohacker** [comment]
I'm going to say this is low priority. Will still move to Sprint 8, but we can figure later.

**Comment by batpad** [comment]
closing. hopefully we can improve this once we upgrade to drf 3.
