### ISSUE TITLE
Add historical IVRS data to SYS DB

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#299]
Also, write code to fetch new data from IVRS API and include failsafe and error checking.

**Comment by harisibrahimkv** [comment]
We are in a position to add historical data to the SYS DB.

Run `python manage.py fetchivrs --from=day/month/year --to=day/month/year`

Running `python manage.py fetchivrs` will fetch today's data.

**Comment by batpad** [comment]
Closing as done.
