### ISSUE TITLE
Cleanup if (document.width() > 768) conditionals in JS

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#336]
1. The Uncommon JS contains a conditional like if (document.width() > 768) in several places which currently have been left as is. This is a very crude way to do device detection, and should ideally be replaced by some better handling in klp.js where it sets some klp.isMobile / klp.isTouch variables that can be used instead of checking document width everywhere.

2. Also in dubdubdub/urls.py there is some code for header_full_width and header_fixed which we can remove later

**Comment by batpad** [comment]
@imohkay can I mark this as closed?

**Comment by imohkay** [comment]
@batpad  think they're all removed... not a 100%sure. Anyways, we can knock them off if we come across them in the JS.
