### ISSUE TITLE
Frontend Refactor: Scope and viability

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#340]
Sub-issues:
#341: Decouple selectors used in JS and CSS 

Just a collection of thoughts about a Frontend refactor:

**Step 1**
- Making sure all JS classes in the current develop branch are prefixed with 'js-' (and no styling is applied to them via CSS). Basically, ensure that behaviour and styling are not too tightly coupled, which would make the rewrite very hard. See #341 
- Remove dependency on the custom jQuery UI, ideally
- Figure out who all on the team are working on the front end, and be in touch with them while the refactor is going on (if so), so there are no major conflicts. And of course, making a note of major frontend changes that are slated to happen over the next 2-3 months.
- Making a note of things that the team may wish to change or update: e.g. moving off Highcharts and any gnarly UX issues that may need a redesign (enhancements more than bugs), and creating a new, additional label in the issue tracker for the rewrite
- Making a note of base styles for all HTML elements, presuming the CMS has richtext/markdown textareas, so styling doesn't get affected by user updated content. I can't seem to find any richtext areas when I looked, though. 
- Document base browser support (perhaps A-grade modern browsers and which ancient browsers or B-grade still need to be supported). IE, Android and iOS, most importantly.
- Looking at the sub-domains and see if new UI components need to be created, so all of them have to potential to have a consistent UI, at some point in the future

**Step 2**
- Make a new branch for this front-end rewrite, from the develop branch
- Keep merging/rebasing develop branch changes into this new branch, so things are in sync. This would possibly get tricky at some point.
-  Remove all the styling and try and keep the current HTML syntax as close to the current is as practically possible. Then start with the CSS from scratch and refactor the JS accordingly.
- Remove all unnecessary conditional code for mobile and desktop and retina screens
- Clean up the JS files
- Making small UI components for UI modules: e.g. modals, accordions, tabs, search filters, etc. that are modular and resuable
- Moving from raster to vector images (also rids us of this ridiculous 2x png stuff) and requesting the designers to provide vectors for several icons and images currently there in the app.
- Move to [autoprefixer](https://github.com/postcss/autoprefixer) for vendor prefixes. This allows us to write regular CSS (via Sass, in our case) and will automatically add vendor prefixes. So we don't depend on a preprocessor for the same. Will add an extra step in building and compiling but is worth it.
- I may get abused for this, but some build or compile tool (like Grunt or Gulp) or simple way to have everything build and compile by running just one command. [Some info here](https://lincolnloop.com/blog/simplifying-your-django-frontend-tasks-grunt/). But then again, Sass is very slow inside vagrant, so maybe not.
- Keep accessibility in mind for users with disabilities, including alt text, labels for forms, wai-aria, headings, etc.

**Step 3**
- A living styleguide that is maintained (possibly by directly accessing production CSS files, so we're in sync)
- Proper documentation for the front end code including preferred naming conventions, spacing and indentation for HTML, CSS, JS

**Comment by imohkay** [comment]
@batpad for what plugin is the custom jQuery UI dependency?

**Comment by batpad** [comment]
oh no, there's a custom jquery ui dependency? :(
err .. not sure :/
