### ISSUE TITLE
Prefix JS classes with js- and decouple from CSS

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#341]
Sub-issue for #340 

Here's a list of selectors which will need to be modified:

**Issue 1: Have styles in the sass files attached to them. **
Solution: Create an additional selector with js- prefixed and use this in the js files. Leave these selectors intact; they can be used for styling.

*Selector list below:*
.error-message
.mt-5 (removed class and added styling in sass)
filter-tool (in map.css)
.imagePreview (also changed class in the lib/jquery.imagepreview.js, sorry about that)

.modal-overlay: TBD
.btn-modal-close: TBD
.tab-content: TBD
.tabs: TBD
.map-canvas: TBD
.search-input: TBD
.profile-options-wrapper: TBD
.show-drop: TBD
.content: TBD
.top-nav: TBD
.main-header: TBD
.options-wrapper: TBD
.modal-map-filter: TBD
.show-volunteer-filters: TBD
.show: TBD
.show-drop: TBD
.hide: TBD
.open: TBD
.active: TBD
.fadein: TBD
.fadeout: TBD
.move-left: TBD
.move-right: TBD
.visible: TBD
.item_values: TDB
.current: TBD
.home-header: TBD: 
    @batpad what in the world is going on with home-header?
.volunteer-filters-wrapper: TBD (tied to show-mobile)
.show-mobile: TBD (@batpad would like to remove this, eventually)

**Issue 2: Selectors used in the JS file, but no styling attached to them **
Solution: Just add a js- prefix to them and ensure they're not attached to any of the existing templates.

*Selector list below:*
.volunteer-filters-dropdown
.confirmVolunteerBtn
.filters-dropdown
.no-data: (Seems to be a highcharts class, so ignoring for now)
volunteerDateModal
apply-selectboxit
.klp
.dise
.data: TBD

Thanks to @batpad for sitting with me on this one :)

**Comment by imohkay** [comment]
@batpad made a feature branch "341jsclasses" for this. Still incomplete, but if you feel like merging into develop branch, that should be fine. Doesn't seem to break anything, but I'm not a 100% sure. Once you merge, just reassign back to me. thanks :)

**Comment by batpad** [comment]
@imohkay this is all done? can close?

**Comment by imohkay** [comment]
@batpad there are still some classes hanging out, but they're mostly ids, so I think it's ok. As a general convention, we can maybe avoid styling any ids, and I'll add that to the styleguide too.
