### ISSUE TITLE
EMS Data Import.

### ISSUE THREAD

**Issue by geohacker** [klpdotorg/dubdubdub#344]
@batpad @iambibhas @vinayakh - Creating this ticket to track the data import. 

Okay, so this what I outline -
1. Introduce academic year into all the databases, create foreign key relationships from all the objects.
2. Regenerate materialized views.
3. Write a script to import the 2012-13 data.
4. Pray.

**Comment by geohacker** [comment]
1. Boundaries.
2. Schools - new schools get created. So need to be tied to academic year.
3. Students data aggregated per class and school. So classes need to be tied to academic year.
4. Assessments - need to be tied to academic year.

**Comment by geohacker** [comment]
1. [ ] tb_institution_agg table will have a foreign key to tb_academic_year
2. [ ] tb_institution_agg table will get a new primary key, which is sequential.
3. [ ] tb_institution_assessment_agg table will have a foreign key to tb_academic_year
4.

**Comment by geohacker** [comment]
Okay, Devi and I started digging into the current scripts and this is what we think is happening -
1. The master script is the [klpwww.sh](https://github.com/klpdotorg/importers/blob/master/klpwww.sh)
2. [klp-exp.py](https://github.com/klpdotorg/importers/blob/master/klp-exp.py) creates CSVs for each table in klpwww. Also created load.sql which has SQL instructions to import the data into the database.
3. And all aggregation happens in [agg.sql](https://github.com/klpdotorg/importers/blob/master/agg.sql)

**Comment by geohacker** [comment]
Process -
1. Add new academic year.
2. Load the schools csv -
  * Add new schools.
  * Update details about old schools.
3. Load boundary csv -
  * Add new boundaries.
  * Update details about boundaries
4. Load class csv - 
  * Add new classes to existing schools.
5. Load student csv - 
  * Add new students.
6. Load student_class csv - 
  * Deactivate the student in the previous year.
  * Add the new student in the class for the current year.
7. Load teacher csv -
  * Add new teachers.
8. Load teacher_class csv - 
  * Deactivate the teacher in the previous year.
  * Add the new teacher in the class for the current year.
13. Load teacher_qual csv - 
  * Add new qualifications.
9. Load programmes csv - 
  * Add all programmes. 
10. Load assessments csv - 
  * Add all the assessments.
11. Load questions csv - 
  * Add all the questions.
12. Load questions_eval csv (answer table)-
  * Add only records with object_id 24.

**Comment by gkjohn** [comment]
Made a few changes @geohacker

**Comment by deviprasadadiga** [comment]
Queries for CSV's

tb_bhierarchy - select distinct id,boundary_category from schools_boundary_category;

tb_boundary_type - select id,boundary_type from schools_boundary_type;

tb_boundary - select id,parent_id,name,boundary_category_id,boundary_type_id from schools_boundary where not name='No Parent';

tb_address - select * from schools_institution_address;

tb_school - select inst.id, inst.boundary_id, inst.inst_address_id, inst.dise_code, inst.name,cat.name, inst.institution_gender, moi.name, mgmt.name, inst.active from schools_institution inst left outer join schools_institution_category cat on (inst.cat_id=cat.id) left outer join schools_institution_languages lang on (lang.institution_id=inst.id) left outer join schools_moi_type moi on (moi.id=moi_type_id) left outer join schools_institution_management mgmt on (inst.mgmt_id=mgmt.id);

tb_child - select c.id,lower(trim(c.first_name)),lower(trim(c.middle_name)),lower(trim(c.last_name)),to_char(c.dob, 'YYYY-MM-DD') as dob, c.gender, mt.name from schools_child c left outer join schools_moi_type mt on (c.mt_id=mt.id);

tb_class - select id,institution_id,name,section from schools_studentgroup where group_type='Class';

tb_academic_year - select * from schools_academic_year;

tb_student - select * from schools_student;

tb_student_class - select stusg.student_id,stusg.student_group_id,stusg.academic_id,stusg.active from schools_student_studentgrouprelation stusg,schools_studentgroup sg where stusg.student_group_id=sg.id and sg.group_type='Class' and stusg.academic_id in (121,122);

tb_programme - select id,name,start_date,end_date,programme_institution_category_id from schools_programme where extract(year from start_date)=2012 or extract(year from start_date)=2013;

tb_assessment - select ass.id,ass.name,ass.programme_id,ass.start_date,ass.end_date from schools_assessment ass,schools_programme p where ass.programme_id=p.id and p.id in (select id from schools_programme where extract(year from start_date)=2012 or extract(year from start_date)=2013);

tb_question - select q.id,q.assessment_id,q.name,q.question_type,q.score_max,q.score_min,q.grade from schools_question q, schools_assessment ass,schools_programme p where q.assessment_id=ass.id and ass.programme_id=p.id and p.id in (select id from schools_programme where extract(year from start_date)=2012 or extract(year from start_date)=2013);

tb_student_eval - select se.question_id,se.object_id,se.content_type_id,se.answer_score,se.answer_grade from schools_answer se,schools_question q, schools_assessment ass,schools_programme p where se.question_id=q.id and q.assessment_id=ass.id and ass.programme_id=p.id and p.id in (select id from schools_programme where extract(year from start_date)=2012 or extract(year from start_date)=2013);

tb_teacher - select t.id,lower(trim(t.first_name)),lower(trim(t.middle_name)),lower(trim(t.last_name)),t.gender,t.active,mt.name,t.doj,type.staff_type from schools_staff t left outer join schools_moi_type mt on (t.mt_id=mt.id) left outer join schools_staff_type type on (t.staff_type_id=type.id);

tb_teacher_qual - select sq.staff_id,qual.qualification from schools_staff_qualification sq,schools_staff_qualifications qual where sq.staff_qualifications_id=qual.id;

tb_teacher_class - select staff_id,student_group_id,academic_id,active from schools_staff_studentgrouprelation;

**Comment by geohacker** [comment]
Thank you @deviprasadadiga.
@batpad @iambibhas  - The above queries generate the CSVs every year. 

@batpad - you want to start a wiki page and document this whole data import stuff?

**Comment by iambibhas** [comment]
Just updates - 

 - `AcademicYear` now has `from_year`, `to_year`
 - `tb_institution_agg` is now `mvw_institution_aggregations` that has `academic_year_id`
 - `mvw_institution_aggregations` has a primary key which is of the format `A<academic_year_id>S<school_id>`
 - not doing anything with `tb_institution_assessment_agg` for now.
 - `tb(student|teacher)_class` already have FK to `academic_year`
 - Divided `mvw_school_details` into `mvw_school_details` (without num_boys/girls) and `mvw_school_extra` (with FK to academic_year).
 - `mvw_school_extra` has a primary key which is of the format `A<academic_year_id>S<school_id>`

Working on the import now. The import script will have some kind of report showing how much data will be updated and created before executing any destructive query, so that we have some idea of what's happening.
