### ISSUE TITLE
Navigation menu: Rework

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#346]
1. Convert the hover on desktop to click: Right now, the menu doesn't work on the iPad on horizontal orientation. This implies an extra page and menu heading in the dropdown menu

2. Fix the header to the viewport:  So the user doesn't have to scroll up to access it I can reduce the height a bit. One advantage is the UI stays the same, including on the map pages as well. 
Will just need to keep an eye on things like sticky scroll stuff on some pages. See #374 

3. Ideally, we should remove the conditional code in the base template and urls.py also (extra_context={
''header_full_width': True, 'header_fixed': True}

4. Active Link Styling: @batpad required?

**Comment by imohkay** [comment]
@batpad could you approve the 2 points above?

**Comment by imohkay** [comment]
@batpad hey... so there's plenty of extra stuff in the urls.py that we don't need now (extra classes for header (full-width, fixed width), extra classes for breadcrumb... safe to remove them and do you feel like doing it? We should keep the hide footer bit though.

**Comment by batpad** [comment]
@imohkay could you go ahead and remove these? would be nice to clean-up. Thanks
