### ISSUE TITLE
Breadcrumb redundancy for UX

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#349]
The breadcrumb a bit out of place, imho. It's useless on the home page, for instance, and the other pages which just have their link and home. e.g. Home > Data for /data.
The only potential useful location seems to be on the map. Even in that case, a simple back button to map on the page should suffice.
A user can just use the logo to navigate to the home page.
If we knock off the breadcrumb, I was considering moving the Login button up to the right of the menu. Will ensure text ellipses on names, if so. Also, then remove the relevant code from /apps/users/views.py

**Comment by imohkay** [comment]
@batpad @gkjohn any feedback on this? Was just a thought I've had since the last few days.

**Comment by gkjohn** [comment]
So the back button does work. Sanjay and Sajjad did some crazy work on
that. If not a bread-crumb, then some way of indicating the tree depth a
user is at? Especially on the map page.


Thank you.

Best,

Gautam
________
http://www.akshara.org.in/

**Comment by imohkay** [comment]
@gkjohn I believe there are only 2 levels map on a map page, right? (excluding home). Map and School name. We could have a back button somewhere, although this won't be necessary if the browser back button works now.

**Comment by gkjohn** [comment]
Technically, there's an entire hierarchy.

District>Block>Cluster>School or
Constituency>School etc.

Depending on the visitor path. @geohacker comments?

**Comment by geohacker** [comment]
@gkjohn This is in the pipeline when we aggregate the data at these hierarchies. Then they will have their own pages and the breadcrumb will change accordingly.

**Comment by imohkay** [comment]
@geohacker then definitely makes sense to have on the map page. though I still wonder if it's needed on the other pages.

**Comment by geohacker** [comment]
Yes. It should be the same all over.
