### ISSUE TITLE
Vectors to be requested from designers

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#350]
- Logo
- Any sketches made using SVGs
- Any icons for which there are SVG or .AI files.

If the design company can do this, it would be ideal if they convert to svg and send across

List includes:
1. Logo
2. Map filter icons (on top right of school map)
3. Boys, Girls, Total icons on Map Modal
4. Facilities icons on Map Modal

**Comment by imohkay** [comment]
@batpad is it possible for me or someone else to get in touch with them, at some point?

**Comment by gkjohn** [comment]
Can do. Angad Kingra <angad@uncommon.is> is the person. Lemme know what I
should ask them for?


Thank you.

Best,

Gautam
________
http://www.akshara.org.in/

**Comment by imohkay** [comment]
@gkjohn thanks :) will make a list as I go along and send when ready.

**Comment by imohkay** [comment]
closing this since we've managed with icon fonts for pretty much everything. if we need the exact same icons for a few things, we can re-open
