### ISSUE TITLE
Use font-icon vectors for icons, where possible

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#351]
1. Move to Font Awesome and replace raster icons, where possible
2. Add more helpful icons throughout the site
3. Move off the CDN to local files at some point
4. Knock off the image rasters from the repo once you're done

**Comment by imohkay** [comment]
@gkjohn hey... possible to ask design firm what font this is? If it's free to use, I'd rather use text than an image. Easier to maintain long term as well... thanks.
![home_headline_text](https://cloud.githubusercontent.com/assets/1667470/5699324/f32cf740-9a4a-11e4-8c1e-4135df2f4b74.png)

**Comment by gkjohn** [comment]
@imohkay Is there a sample of the font I can point them to?

**Comment by imohkay** [comment]
@gkjohn On the home page, the black banner section, just below the colored logo, is the text, "Come engage with us and help us make our schools better for our children."
This is currently an image, would be nice to know which font they used to create the image.
