### ISSUE TITLE
Base browser support

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#356]
I would like to do the responsive bits of the site using min-width media queries. The only downside is that IE 8 will be served the mobile layout. The advantages are much leaner CSS and less overriding of classes.
Also, I'd like to use some modern ways to code, which may make the layout a bit more boring on IE 8 and 9, only in 3-4 places, if that's okay.

**Comment by imohkay** [comment]
@batpad can we consider IE8, Android < 4.4 and iOS < 6 as B-Grade browsers and the rest as A-Grade? The site will still work properly, but there may be tiny layout issues in a couple of places.

**Comment by batpad** [comment]
@gkjohn can you confirm if this is okay?

**Comment by gkjohn** [comment]
Yes it is.


Thank you.

Best,

Gautam
________
http://www.akshara.org.in/
