### ISSUE TITLE
Tab to accordion on mobile - responsive

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#358]
Create widget for this so there's no duplication of code for the same in the templates
- Ensure if text is long, that we scroll back to the content on clicking an accordion link

**Comment by imohkay** [comment]
@batpad will sit with you for the JS on this, eventually.

**Comment by imohkay** [comment]
@batpad hey... so I've improved the styling of the accordion on mobile now, so it's a bit more obvious what it is. I also realized that that jump to the top is a bit confusing for the user on mobile. could you add a teeny weeny animation while the scrollTop function is happening, so it's more obvious what's going on?

**Comment by batpad** [comment]
@imohkay I believe this is all done. closing.
