### ISSUE TITLE
Select2 plugin styling

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#363]
Sub-issue for #367

- Style base select 2 select to match old Design styleguide
- Ensure this is consistent for all select2 selects.

I have seen 2 styles of select2:
1. Search on school map
2. School type in the modal for map filters (click second of 3 icons on top right of school map to get here)

**Comment by batpad** [comment]
@imohkay ask @geohacker about the styling of the select2 inside the filters modal on the map page, they're a bit that way for a reason -- I think the select2s there can have different styling - but select2 search on map page + the select2 on the compare modal should probably be styled the same ..

**Comment by geohacker** [comment]
@batpad Err, I think they should be styled same.

**Comment by imohkay** [comment]
@batpad closing this one. i occasionally see a FOUC, can look into that later...
