### ISSUE TITLE
Notifications at top of the viewport: Forms

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#366]
Sub-issue for #367

1) Make these fade out, they look a bit odd sliding up or improve the animation.
2) The yellow color with grey text is very hard to read. Example, on the modal triggered by clicking the second filter on the top right for the school map, the No Location Data in yellow.

**Comment by imohkay** [comment]
@batpad, besides the green and yellow colors, are there any other states for notifications, that I've missed or we need?

**Comment by batpad** [comment]
@imohkay yea, that yellow is a mistake and needs to be fixed. There is also an "error" state which is red background with white text. I think you can trigger it on any page by typing something like this in console:

    klp.utils.alertMessage("Some test message", "error");

**Comment by imohkay** [comment]
@batpad hey on the frontend-refactor branch, not able to replicate that yellow notification anymore... (perhaps because it doesn't have any references to the older sass files?) could you test and let me know? I can then close issue. see description of this issue to jog memory, if required.

**Comment by imohkay** [comment]
@batpad sorry so I tried, but cannot replicate... can you try and let me know if you see the notification and it looks weird?

**Comment by batpad** [comment]
@imohkay you seem to have a default styling for them with a blue background now that looks fine / great.
If there's nothing left on this, please close issue?
