### ISSUE TITLE
Autoprefixer for vendor prefixes

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#372]
I'd like to use autoprefixer so we can just write regular CSS and not worry about prefixes. This adds a node.js dependency, since it's an npm install.

**Comment by imohkay** [comment]
@batpad, should I go ahead with this? I'll need some help here, to figure out how to do this for staging and production.
Also, ideally, it should watch all the time, which I've been unable to figure.

**Comment by batpad** [comment]
hrm - not super happy with the idea of adding a node js dependency to the work-flow .. but I think we'd do it like we currently do the SASS - i.e. just do the compile on local machine and add all the compiled files to repo and push so we don't need to do the compilation on server. In that case, I think it should be fine..

**Comment by imohkay** [comment]
@batpad decided not to go with autoprefixer, so closing this 'un
