### ISSUE TITLE
Datepicker: Currently not responsive

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#375]
On Volunteer Map Page, seems to use Zebra Datepicker, which is non-responsive.

**Comment by imohkay** [comment]
@batpad, should we move to something responsive like pickadate,js, or let things be as they are?

**Comment by imohkay** [comment]
batpad told me yes, although I can't exactly prove it.

**Comment by batpad** [comment]
@imohkay here is proof: yes :)
also, let's then use pickadate across the site wherever we're currently using input type="date" - once you have pickadate integrated, you can assign that bit to me. thanks.

**Comment by imohkay** [comment]
@batpad i've closed this... presume it works fine for places where it's dynamically appearing?
