### ISSUE TITLE
Volunteer map

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#376]
@batpad sorry for the questions below:

1. Is there a page with some real events? Is the styling for these the same as the current design styleguide?
2 Can we have the map on mobile as well? Not sure why it's hidden.
3. A start and end date would be nice here, I would think.
4. What in the world is all this slimScrollbar stuff? Let's knock it off?

**Comment by batpad** [comment]
@imohkay lets discuss this when we meet and also add some test data to your dev instance .. there's some specific reasons for the date thing as well as hiding map on mobile. Can discuss when we meet. Thanks.
