### ISSUE TITLE
Map: Z-index

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#378]
Sub-issue for #382 

The z-indexes on the school map are sometimes broken, specially if you resize the window at around 850-900px.
![map-zindex](https://cloud.githubusercontent.com/assets/1667470/5643760/3f370ca6-9682-11e4-8cac-a9b2a642693d.jpg)

**Comment by geohacker** [comment]
@imohkay this is not because z index is broken, it's because the map div is not fixed. We should ideally make the filter and that bar should not be floating.

**Comment by imohkay** [comment]
@geohacker the map is fixed, but there isn't enough padding from the top. It's an easy fix (changing top value of map_canvas_full class), but I'll do it later.
