### ISSUE TITLE
Map: Filters

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#381]
Sub-issue for #382 

These are the icons on the top right of the school map.

1. Ideally, the first one should show up its menu on click and not hover, which makes accessing the other filters hard. @batpad, can I go ahead with this?
2. You can't close a school near the icons: A possible solution is to have a close button at the bottom. @batpad, do you concur? UI issue. See attached image.
3. Provide a small box-shadow: Filters and leaflet zoom icons blend in with leaflet popup if they collide. See attached image.

![map-school-close-overlap](https://cloud.githubusercontent.com/assets/1667470/5643836/e4759746-9682-11e4-8403-9b8106afb50d.jpg)

.

**Comment by geohacker** [comment]
@imohkay These are not easy to fix and I don't think any of this can be fixed via CSS or reasonable JS. These are all under Leaflet and we can come back to it later, is what I suggest. @batpad
