### ISSUE TITLE
JS: Remove extra files at some point

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#387]
Some useless files lying around the repo need to go:
- main.js
- libs.combined.js
- lots of code for steps in form (which is not being used anymore, I believe
- perhaps replace the show-drop js for login with the current code used for the nav dropdown
- /static/js/volunteer_map/volunteer_date_modal.js : can remove later if not using

**Comment by batpad** [comment]
To add:

- everything in assets/static/js/klp/
- everything in assets/static/js/legacy/

**Comment by imohkay** [comment]
@batpad you mean delete all these files, right?
can't find legacy folder.
