### ISSUE TITLE
New API end-points for MP and MLA boundaries

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#392]
Need end-points to:

- List all MP boundaries
- List all MLA boundaries inside an MP boundary
- List all Wards inside MLA boundary

**Comment by iambibhas** [comment]
Added these endpoints - 

http://localhost:8001/api/v1/boundary/assemblies
http://localhost:8001/api/v1/boundary/parliaments
http://localhost:8001/api/v1/boundary/parliament/6/assemblies

**Comment by iambibhas** [comment]
@batpad lemme know if they look good. I'll close this.

**Comment by batpad** [comment]
Sorry left this open - this seems done and can be closed. @iambibhas please re-open if you feel something is remaining here.
