### ISSUE TITLE
Banners - full-width: Make modular and responsive

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#402]
E.g. The banner below the navigation on /programmes/foo

1. Current code has some JS to re-size, which can be removed.
2. Make code re-usable.
3. On the library page, the banner image on mobile loses focus, because the meat of the images is at the edges. See if there's a tighter crop available around.
4. Visibility of text overlaying some banners is very poor. See if you can add a semi-transparent overlay, so it're more readable

**Comment by imohkay** [comment]
@batpad is the same banner image on the /programmes/reading and /programmes/sikshana intentional? because their style guide seems to have different banner images.

**Comment by imohkay** [comment]
@batpad is the same banner image on the /programmes/reading and /programmes/sikshana intentional? because their style guide seems to have different banner images.

**Comment by batpad** [comment]
@gkjohn do you know this? should the the programmes pages have different banners? if yes, do you know where these banners are, etc? Thanks.

**Comment by gkjohn** [comment]
Ummmm, rather basic question, @batpad, what do you mean by banners? :(

**Comment by batpad** [comment]
@gkjohn lol - I think @imohkay means the big, slightly blurry images at the top of these pages:

https://klp.org.in/programmes/reading/
https://klp.org.in/programmes/sikshana/

Currently they're the same image. Do they need to be different? Thanks.

**Comment by gkjohn** [comment]
They are different on other prorgam pages. For Sikshana, they didn't send us one. Hence, reused. 

See https://klp.org.in/text/maths/

**Comment by imohkay** [comment]
@gkjohn cool... in general, this issue is also done, so binning it :D
