### ISSUE TITLE
Modals: Have login as default view

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#411]
@batpad @gkjohn 

For the login modal, the default view when you click login is the Signup section. Could we instead, have the Login section as the first screen, with the signup button below? I would presume it would benefit most users, although I could be wrong.

Update: fix text since login is now default view.

**Comment by gkjohn** [comment]
Of course! Please make the change @imohkay

**Comment by imohkay** [comment]
@gkjohn yaay. @batpad assigning to you :P
