### ISSUE TITLE
Datepicker: Check and enable functionality

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#415]
@batpad styling works. 
plugin is http://amsul.ca/pickadate.js/
Enabled on e.g. organisation/1/volunteer_activity/1 for Date
@batpad please fix datepicker on share story tab to be instantiated after the form appears

**Comment by batpad** [comment]
@imohkay please re-open if datepicker doesn't work anywhere, but I believe this is all done.
