### ISSUE TITLE
Multiple dropdown menus: Handling closing events 

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#419]
Currently for profile menu and navigation menu, both close on the window.click event. We need to handle behaviour when multiple menus are triggered. Ideally, re-use the navigation dropdown code for the profile options.

**Comment by imohkay** [comment]
@batpad can this be fixed by the end of this sprint?

**Comment by batpad** [comment]
@imohkay oh. sure. missed seeing that. What do you need to happen / can you give me a test case to reproduce the problem?

**Comment by imohkay** [comment]
@batpad resize the window till both the icons show up (hamburger menu icon and profile icon side by side)... and then click both and see what happens
