### ISSUE TITLE
Change Programmes to Partners

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#426]
Since we now have data from multiple Partners.

**Comment by batpad** [comment]
@gkjohn just the menu heading, or in other places as well?

**Comment by gkjohn** [comment]
Ooops. Where else is it @batpad?

**Comment by batpad** [comment]
oh no, was just checking if there was other places, heh .. cool, so just the menu then .. should we, ideally, also change the URL to be /partners/ ... ? @gkjohn

**Comment by gkjohn** [comment]
There might be other places where it's referred to as programmes. Not sure. Can you grep the code to see? And yes, change URL to partners as well. @batpad

**Comment by imohkay** [comment]
@gkjohn @batpad what about urls like this one? http://dev.klp.org.in/text/library/

**Comment by gkjohn** [comment]
Good catch. Should we standardise to:

partners/organisation_name/program_name

So this will be:

partners/akshara/library

And the other Akshara ones will be:

partners/akshara/reading
partners/akshara/maths

And Sikshana will be:

partners/sikshana/reading

etc @imohkay

**Comment by imohkay** [comment]
@batpad should I go ahead and change the urls above in the .py file? Or something I need to know before I do?

**Comment by batpad** [comment]
@imohkay na, I'll make these changes. We may want to setup redirects from the older URLs and such.. will go over those changes to the pages with @gkjohn and then discuss those with you to see if you could take care of the content changes or if its easier for me to just do that. thanks.

**Comment by batpad** [comment]
URLs changed, deployed to dev..
