### ISSUE TITLE
Consolidate questions in SYS

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#438]
Right now, we have the same question asked across different sources in different question groups. Ideally, we would consolidate these into the same question, so we can aggregate questions across different sources / question groups.

4 questions identified to consolidate would be something like:
 - Was the school open? / How many schools were open?
 - Was the teacher present? / How many have teachers present?
 - Were classes going on? / How many schools had classes going on?
 - Did school have a toilet? / How many schools had functioning toilets?

We need to identify these questions across all sources, and then "merge" them. @harisibrahimkv lets discuss  this when you're back and see if its something you can take up. @gkjohn does this seem like a reasonable thing to do?

@meghaklp mentioning you on this as well so you can keep a track of status. Thanks.

**Comment by gkjohn** [comment]
Yes, this seems like a sensible thing to do. Currently, do we not do it in SYS DB?

**Comment by batpad** [comment]
@gkjohn the schema supports it, but we currently haven't merged any questions yet - was just too chaotic at the time of import .. but this is definitely we should do now.

**Comment by gkjohn** [comment]
Ah. Okay. Yes, should do it now.

**Comment by batpad** [comment]
Seems like we have discussed this and put it off for later. Am closing this for now.
