### ISSUE TITLE
Add user_type to Question table

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#441]
We need to mark questions as being applicable to only a particular user type - for eg. questions that are asked only to Teachers, only to SDMCs, etc.

Related: should we make User Type another table and have a ForeignKey, or just have it a choices / enum?

tag: @harisibrahimkv @meghaklp

**Comment by harisibrahimkv** [comment]
@batpad Implementing user_type as another table. Otherwise having the choices field on both the Story and Question model seems redundant. Can't think of any obvious reasons not to have this as a separate table.

**Comment by batpad** [comment]
@harisibrahimkv a separate table for user type and foreign key seems perfect. please go ahead. thanks.

**Comment by meghaklp** [comment]
User type = Respondent type? I  am not sure u need to tie a question to the
respondent/user type, no? You need tie the answer/story to the respondant

**Comment by batpad** [comment]
@meghaklp when there are questions that are only applicable to eg. Teachers, it would be nice to store that information in the Question model.

@harisibrahimkv of course, that column should be NULLable, since by default, questions are applicable to all user types.

@meghaklp does that make sense?

**Comment by meghaklp** [comment]
@batpad I guess like metadata on the question sounds okay. But we'll
capture respondent type also..

**Comment by batpad** [comment]
@meghaklp of course.

**Comment by harisibrahimkv** [comment]
The migration https://github.com/klpdotorg/dubdubdub/commit/77323ca92eb6acdb15aa84ab934fc40f4d620d28 implements this issue.

Also implements UserType as a separate model. https://github.com/klpdotorg/dubdubdub/commit/1aca6ac49f8ad94515180ffd9b13f2257e54f033
