### ISSUE TITLE
User types for non-Community Feedback questions

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#442]
Soo .. the current plan was to add a user_type column in Story to store user_type, and leave this NULL for existing stories.

@gkjohn the question is: is it possible to auto-fill some respondent / user type for the existing stories? i.e. are all web stories submitted by volunteers? all IVRS by something .. ? This would help to show stories shared by respondent type aggregated across the different sources.

@meghaklp can you expand on this a bit? How do you see us mapping existing stories from web / ivrs to respondent / user types?

Thanks.

**Comment by gkjohn** [comment]
@batpad Yes. Web can be volunteers. IVRS is AF field staff.

**Comment by batpad** [comment]
This has been answered. @harisibrahimkv nothing pending to know on this, right? Closing.
