### ISSUE TITLE
Define respondent types

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#444]
Can we please make a list of user types?

 - Parents
 - Teachers
 - Educated Youth
 - SDMC Member
 - Volunteer
 - Akshara Staff
 - CBO Member

@gkjohn can you add / remove from this list?

**Comment by gkjohn** [comment]
* Parents
* Teachers
* Educated Youth
* SDMC Member
* Volunteer
* Akshara Staff
* CBO Member
* Headmaster
* Elected Representative 
* Education Official

**Comment by meghaklp** [comment]
- Local Circle / Data Collectors

**Comment by batpad** [comment]
I think this is done. Closing.
