### ISSUE TITLE
Placeholder here for Wireframe updates

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/dubdubdub#445]
![stories_v1_with_comments](https://cloud.githubusercontent.com/assets/465382/6245283/f9eb6378-b782-11e4-83c1-941c85ea04eb.jpg)
![stories_v1](https://cloud.githubusercontent.com/assets/465382/6245284/f9f0313c-b782-11e4-8116-c3bd22c89555.jpg)

**Comment by gkjohn** [comment]
Yes, @meghaklp?

**Comment by meghaklp** [comment]
Nothing for now @gkjohn I unassigned you - There should be a way of adding participants to a ticket.

**Comment by batpad** [comment]
@meghaklp yea, I think the best way is to just @ them in a comment ..

**Comment by meghaklp** [comment]
![stories_v2](https://cloud.githubusercontent.com/assets/465382/6247239/0779f5d0-b798-11e4-9125-2955de2359b2.jpg)

**Comment by meghaklp** [comment]
@imohkay , @gkjohn , @batpad  - That's everything now! That can go on the dashboard. Cluttered for a web view, unless you keep collapsing the sections.

**Comment by gkjohn** [comment]
@meghaklp Looking good. I'd ask for some text changes, for example, instead of Total Count of Stories I'd say "Stories Received" or something like that. Keep it more conversational. Also, on all charts whether  there is a way to show percentages or something too?

**Comment by meghaklp** [comment]
@gkjohn - I'll look at the labels again.
And.. I'll be experimenting with a few charting libraries. Let's see what they allow for. If we can's show them on the chart we'll show them next to...Some have actual numbers here, some don't. Maybe everything should be shown as a percentage for consistency. I'll think about that too.

**Comment by meghaklp** [comment]
![story dashboard - karnataka learning partnership](https://cloud.githubusercontent.com/assets/465382/6597454/d793387c-c822-11e4-8aed-d21d241b667b.png)

**Comment by meghaklp** [comment]
![story dashboard - karnataka learning partnership 1](https://cloud.githubusercontent.com/assets/465382/6597463/ea4e20a8-c822-11e4-821b-946bbda6b78c.png)

**Comment by meghaklp** [comment]
![story dashboard - karnataka learning partnership 1](https://cloud.githubusercontent.com/assets/465382/6597613/e9f6f5f2-c823-11e4-8fd3-dc3e54209ee3.png)

**Comment by meghaklp** [comment]
![stories_v4](https://cloud.githubusercontent.com/assets/465382/6848609/415a0cc2-d3f4-11e4-82f7-709514fd63cf.png)

**Comment by meghaklp** [comment]
Now in feedback and improvement.
