### ISSUE TITLE
Possible/Worth putting an [x] or [Close] Button? 

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#447]
On these pages? 

http://dev.klp.org.in/school/33133/#?tab=info

Because the only other way to get back to the map is the back button or the breadcrumb trail.

**Comment by imohkay** [comment]
@batpad assigning to you if you feel this is something we need to do?

**Comment by batpad** [comment]
Since its a separate page, dont think an X button really makes much sense. Closing.
