### ISSUE TITLE
Clean-up answers in SYS

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#450]
Answer data can be really messy. Esp. for boolean type responses, define allowed valid responses and map all existing answer texts to valid responses.

**Comment by harisibrahimkv** [comment]
Implemented in https://github.com/klpdotorg/dubdubdub/commit/214a767010be47ab5016c1b0007ee40806b20ea6

**Comment by batpad** [comment]
Closing as done.
