### ISSUE TITLE
Stories endpoint needs URL param validation

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/dubdubdub#453]
The stories endpoint has a way of passing in a query parameter to pull only verified stories. Like so: /api/v1/stories/?school_id=29600&verified=[yes|no]

There's no URL parameter validation for the verified field. When *any* value is passed in for verified, the API still returns all the stories. Eg. /api/v1/stories/?school_id=29600&verified=somethinginvalid will also return all stories.

Param validation needs to be enforced and only values of yes/no should be accepted. Else, a 400 application error should be returned with the error message clearly indicating the correct parameters to pass in.

**Comment by iambibhas** [comment]
I think it was a design decision to return all the stories(verified and unverified) by default. and one can filter using the `verified` param.

Yeah, it makes sense to add a check to return error if `verified` param is passed and anything other than yes or no is given as value.

**Comment by batpad** [comment]
Have added the query param checks and ensured tests pass. Closing.
