### ISSUE TITLE
Write clear docs for importing SYS data (IVRS, community, etc)

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#465]
@harisibrahimkv can you please make a document, perhaps on the wiki, that clearly documents the process to ingest all this SYS data -- nothing too fancy, just the order of steps in which the management commands should be run, etc. - include both IVRS and community feedback data.

**Comment by harisibrahimkv** [comment]
https://github.com/klpdotorg/dubdubdub/wiki/Import-Scripts
