### ISSUE TITLE
Write out DISE errors to log file (fetchcommunityv2)

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#468]
Right now, the script prints those errors. Just worried that output redirecting that to a file may not quite work since the terminal also prints a lot of other things that would get mixed up?

Maybe nice to just write those errors clearly into a text file? Perhaps as a JSON string so it can be ingested into a script easily?

Something like:

     dise_errors = []
    ....
        if error:
            dise_errors.append(code)
    ....
    outfile.write(json.dumps(dise_errors, indent=4))

Again, not a huge deal how this is implemented -- just want to make sure we don't lose a track of these errors / can easily re-run something to check for just these ids after updating DISE codes in the db, etc..

**Comment by harisibrahimkv** [comment]
@batpad This only needs to be done for the DISE codes script right? Both the IVRS and V1 scripts have school ids that don't match with the ones in the db. Should they too be logged?

**Comment by harisibrahimkv** [comment]
Keep this http://pastebin.com/gAnkk67Y as just a reference. This is the log from running the script locally.

**Comment by batpad** [comment]
@harisibrahimkv oh, we should probably log the unmatched school ids as well :(

My *guess* is this maybe a bit better if we run things after we've imported fresh school data from the EMS ... I think when running these import scripts on prod and dev, we should probably wait for the imports to be done first. Shall co-ordinate with @iambibhas . Even if you can just output the mismatched school ids as a JSON right now, that would probably be useful to check if they exist in EMS ..?
