### ISSUE TITLE
Clarify documentation for fetchivrs date format

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#469]
Maybe just edit the examples in the code to clarify format:

i.e. that it expects 01/01/2013 and not 1/1/2013 .. ideally, also output an error if passed in a param missing padding 0 ..

**Comment by harisibrahimkv** [comment]
Fixed in https://github.com/klpdotorg/dubdubdub/commit/adda9cfef52a6b9ac45b5eecaedb7469791d97d3
