### ISSUE TITLE
Add some docstrings to story API views

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#479]
@harisibrahimkv just some basic docstring with the filters / query params expected, etc. - that will get automatically parsed and displayed as documentation on the API docs page and at the top of the web API browser .. see for ref: https://github.com/klpdotorg/dubdubdub/blob/develop/apps/schools/api_views/school.py#L11

**Comment by harisibrahimkv** [comment]
Fixed in https://github.com/klpdotorg/dubdubdub/commit/130fff6eee6ecc9d28fcb5b1334c670b0e6ec1af
