### ISSUE TITLE
Return months at /stories/volume/ end-point either as ordered dict or list with months in order

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#480]
Please? :)

**Comment by batpad** [comment]
While we're at it, could you send month names abbreviated? i.e. Jan, Feb, Mar, etc. instead of January, February, March .. I think change the strftime("%B") to %b ? Thx :)

**Comment by harisibrahimkv** [comment]
Fixed in https://github.com/klpdotorg/dubdubdub/commit/3526921
