### ISSUE TITLE
On Anganwadi Pages

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#493]
http://dev.klp.org.in/school/30310/#?tab=info

No Finances, Library or Nutrition tabs please. 

Also, Brijesh really should get the Anganwadi Infrastructure data in the SYS DB.

**Comment by batpad** [comment]
Have removed those tabs from preschool pages. Closing this issue, making a separate one for getting Anganwadi Infra data into SYS.
