### ISSUE TITLE
Consistency of URLs

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#495]
Possible for it to say preschools for preschool related URLs and schools for school related URLs. Or just to say institution for both?

**Comment by batpad** [comment]
@gkjohn separating them out in /school/ and /preschool/ is probably a bit of work, yes. I know we have a ticket for this and I'd looked into it and its a bit non-trivial. Changing to /institution/ should be fine. Should we do that?

**Comment by gkjohn** [comment]
@batpad Chang to /institution/ then. But since we have a ticket for /school and /preschool, would be a nice to have at some time.

**Comment by batpad** [comment]
Closing as duplicate.
