### ISSUE TITLE
Add cronjob to fetch IVRS data

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#506]
We need a cronjob to run something like:
  python manage.py fetchivrs --from=dd/myy/yyyy --to=dd/mm/yyyy with yesterday / todays date or do.

@harisibrahimkv assigning you to this here but am also creating a Trello card for Vamsee. Would essentially mean co-ordinating with Vamsee to make this happen. Thanks.

**Comment by batpad** [comment]
cronjob should be run as user dubdubdub and after activating the dubdubdub virtualenv. To activate virtualenv:

    source /home/dubdubdub/dubdubdub/bin/activate

**Comment by gkjohn** [comment]
Adding: 

1. Duplicate checking - for example, if you run overlapping date ranges. 
2. Would be nice to expose this in KLP Admin so it can be manually run too for date ranges.

**Comment by vamsee** [comment]
Hey @harisibrahimkv it looks like you're logging to ivrs_error.log. Perhaps better to add a date to it, something like 'ivrs_error_22052015.log' so it won't overwrite existing log? Also, place the logs in /var/log/ivrs/ - so the path becomes something like /var/log/ivrs/error_22052015.log. What do you think? We could create the /var/log/ivrs dir (if it doesn't exist) at the beginning of the script.

**Comment by vamsee** [comment]
Actually, I think it's better to log to /tmp coz it needs sudo perms otherwise. Anyways with cron we're going to push everything into /dev/null.

**Comment by batpad** [comment]
@vamsee not possible to just create a folder like /var/log/ivrs and make it owned by user 'dubdubdub' ? It maybe nice to have date-wise logs to be able to check up if things go wrong ..

**Comment by vamsee** [comment]
@batpad sure, if required, why not.

**Comment by vinayakh** [comment]
@vamsee @batpad Why not use something like logrotate - http://linuxcommand.org/man_pages/logrotate8.html

**Comment by vamsee** [comment]
@vinayakh gah. Why didn't I think of that. Thanks.

**Comment by vamsee** [comment]
Done, @harisibrahimkv please update the log path in the script to '/var/log/ivrs/error.log'.

**Comment by harisibrahimkv** [comment]
Fixed in https://github.com/klpdotorg/dubdubdub/commit/6dc84eea36d674dabb387dac59cb7dcb024e7750
