### ISSUE TITLE
Get Anganwadi Infra data from EMS

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#507]
We need to import Anganwadi infrastructure data from Anganwadi Assessments in EMS. One idea was to export from EMS and import it as another Share Your Story in our db. And then call the SYS API from the Infrastructure tab on preschool pages and fetch and display the data.

Assigning to myself, but @harisibrahimkv may need you to help with this and Brijesh's.

**Comment by harisibrahimkv** [comment]
Implemented in https://github.com/klpdotorg/dubdubdub/commit/7fc2bca363951643dd08cbc4c459c5fe6dfbbbe8
