### ISSUE TITLE
Mark all stories coming from non-web sources as verified

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#512]
@harisibrahimkv can you, in your import scripts, mark Stories as is_verified=True ?

I have added a management command mark_sys_verified to do this for all the older stuff, but will be nice for new imports if this is done in the import script.

**Comment by harisibrahimkv** [comment]
@batpad For newer ones that I might write? Or for the existing ones? Asking because the existing ones have already been run, right?

**Comment by batpad** [comment]
@harisibrahimkv hrm, ideally for all the existing ones as well, please, if its just a small change?

**Comment by harisibrahimkv** [comment]
Fixed in https://github.com/klpdotorg/dubdubdub/commit/ac32b7c2bf45e1b2824b0acec1563ee5f3ab7cac
