### ISSUE TITLE
Recreate new SYS Web form

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#528]
with new questions and a bit of different design, using radios, etc.

**Comment by meghaklp** [comment]
![web](https://cloud.githubusercontent.com/assets/465382/7708122/4f4e13d0-fe71-11e4-9351-82e8de0588e8.png)
![mobile](https://cloud.githubusercontent.com/assets/465382/7708124/50877fe8-fe71-11e4-9751-01f5cabf5217.png)

**Comment by meghaklp** [comment]
Back to the days of a hideous long form, but I can't see how we can capture this info in a more compact way. I could experiment if there are other suggestions.
@batpad I have a few issues with the calendar widget, this page is tending to have multiple forms and the file -drag&drop uses something called dropzone, not sure if we should use the jquery plugin instead.

**Comment by gkjohn** [comment]
*sigh* @meghaklp what if we did a couple of things. Grouped the questions and made them accordions. And instead of radio boxes used drop downs?

**Comment by meghaklp** [comment]
Actually drop downs need more mouse clicks. And really for 3 choices a drop down maybe an overkill. Trying to find some legit articles on this.

Grouping & accordions are do-able. It's a daunting form still. By the time I get to the last 1/2, I may have lost it.

**Comment by gkjohn** [comment]
Is it worse than the earlier one? If not, is *acceptable* 

Alternatively, what if we made it a wizard? Like a step by step thing?

1. Personal Information
2. Date of Visit
3. Question Group 1
4. Question Group 2
5. Question Group 3
6. Comments & Pictures
7. Submit

And can skip sections/questions too.

**Comment by meghaklp** [comment]
Wizard sounds nice actually! We can scroll to a part of the page on "Next" / "Continue". It'll be nice on the mobile. I'm yet to imagine this on the web form.

Also I thought, if we shortened the questions, say for example:
Did you know if the school has:
Toilets (with icon)  ()Yes () No () Don't Know
Playground           ()Yes () No () Don't Know

Might look less daunting also.

**Comment by gkjohn** [comment]
Easy on mobile too. Like the a checkout on an eCom? Except you refresh the same div? Or move through divs or expand accordions? And progress indicator like: http://i.stack.imgur.com/SHuTx.jpg or http://i.stack.imgur.com/Z5UQV.jpg

**Comment by meghaklp** [comment]
![step1](https://cloud.githubusercontent.com/assets/465382/7818036/bc7e47f6-03f6-11e5-8edb-ec33e47b7ddf.jpg)
![step1_mob](https://cloud.githubusercontent.com/assets/465382/7818037/bc8fae88-03f6-11e5-87c6-a0a07b475e3c.jpg)
![step2](https://cloud.githubusercontent.com/assets/465382/7818038/bc902822-03f6-11e5-974c-d0e1547bbf71.jpg)
![step4](https://cloud.githubusercontent.com/assets/465382/7818039/bc99daa2-03f6-11e5-9cac-5ec15ded8c31.jpg)
![step4_mob](https://cloud.githubusercontent.com/assets/465382/7818040/bca0063e-03f6-11e5-948d-29e312fca40e.jpg)

**Comment by gkjohn** [comment]
@meghaklp This is looking great!

**Comment by meghaklp** [comment]
@batpad Bumping up this as well. Branch is called sys-form

**Comment by batpad** [comment]
done. deployed. closing.
