### ISSUE TITLE
Boundary aggregated data API

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#541]
This ideally needs to support the front-end for boundaries that @meghaklp is working on as WELL as the reports app. Need to discuss exact requirements, etc. with Devi as well.

**Comment by iambibhas** [comment]
Here is the wiki page with all the points - https://github.com/klpdotorg/dubdubdub/wiki/Aggregations-and-Assessments-notes

One problem - Talked Devi. Seems like we have MDM data only for 12-13. So we can only generate MDM aggregations for that acyear.

**Comment by batpad** [comment]
@iambibhas closing this - please re-open if you think anything is pending.
