### ISSUE TITLE
New IVRS Questions for Schools

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#546]
1. Was the school open?
2. Was there a teacher present in each class?
3. Are all the toilets in the school functional?
4. Does the school have a separate functional toilet for girls?
5. Does the school have drinking water?
6. Is a Mid Day Meal served in the school?

**Comment by gkjohn** [comment]
1. ಶಾಲೆ ತೆರೆದಿತ್ತೆ?
2. ಪ್ರತಿ ತರಗತಿಯಲ್ಲಿ ಶಿಕ್ಷಕರು ಇದ್ದರೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
3. ಶಾಲೆಯಲ್ಲಿನ ಎಲ್ಲಾ ಶೌಚಾಲಯಗಳು ಕಾರ್ಯ ನಿರ್ವಹಿಸುತ್ತಿದ್ದವೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
4. ಶಾಲೆಯಲ್ಲಿ ಹೆಣ್ಣು ಮಕ್ಕಳಿಗೆ ಕಾರ್ಯ ನಿರ್ವಹಿಸುವ ಪ್ರತ್ಯೇಕ ಶೌಚಾಲಯ ಇದೆಯೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
5. ಶಾಲೆಯಲ್ಲಿ ಕುಡಿಯುವ ನೀರು ಇದೆಯೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
6. ಶಾಲೆಯಲ್ಲಿ ಮಧ್ಯಾನ ಭೋಜನ ಕೊಡಲಾಗುತ್ತಿದೆಯೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)

**Comment by harisibrahimkv** [comment]
Implemented. Details here: https://github.com/klpdotorg/dubdubdub/blob/develop/apps/ivrs/INFO.txt#L24
