### ISSUE TITLE
New Community Questions for Schools

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#548]
1. Are all the toilets in the school functional?
2. Does the school have a separate functional toilet for girls?
3. Does the school have drinking water?
4. Is a Mid Day Meal served in the school?
5. Have you visited your child's school in the last 3 months? (Yes=1,No=2,Do not know=3,Not answered=4)
6. Are most Teachers Regular in the school? (Yes=1,No=2,Do not know=3,Not answered=4)
7. Do the teachers take clasess regularly?(Yes=1,No=2,Do not know=3,Not answered=4)
8. Is there a teacher shortage in the school?(Yes=1,No=2,Do not know=3,Not answered=4)
9. Do you think your child can read Kannada?(Yes=1,No=2,Do not know=3,Not answered=4)
10. Do you think your child can read English?(Yes=1,No=2,Do not know=3,Not answered=4)
11. Do you think your child can do addition?(Yes=1,No=2,Do not know=3,Not answered=4)
12. Do you think your child can do subtraction?(Yes=1,No=2,Do not know=3,Not answered=4)
13. Are you satisfied with the MDM served in your child's school?(Yes=1,No=2,Do not know=3,Not answered=4)
14. Is SDMC functioning effectively in the school?(Yes=1,No=2,Do not know=3,Not answered=4)
15. Do you check your childs progess card regularly? (Yes=1,No=2,Do not know=3,Not answered=4)
16. Do you send your child for private tution? (Yes=1,No=2,Do not know=3,Not answered=4)
17. Do you think Govt schools are better than Private schools?(Yes=1,No=2,Do not know=3,Not answered=4)
18. Are you satisfied with the MDM served in your child's school?(Yes=1,No=2,Do not know=3)

**Comment by harisibrahimkv** [comment]
Implemented.

Refer questions: https://github.com/klpdotorg/dubdubdub/blob/develop/apps/stories/management/commands/populatecommunitydatav4.py

Refer parsing script: https://github.com/klpdotorg/dubdubdub/blob/develop/apps/stories/management/commands/fetchcommunityv4.py
