### ISSUE TITLE
GKA IVRS Questions

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#549]
1. Was the school open? (Yes=1 and No=2) [Skip all the rest if No]
2. Class visited (4th=4 and 5th=5)
3. Was Math class happening on the day of your visit? (Yes=1 and No=2) [Skip to 9 if No]
4. Which chapter of the textbook was taught? (refer the list 1)
5. Which Ganitha Kalika Andolana TLM was being used by teacher? (refer the list 2)
6. Did you see children using the Ganitha Kalika Andolana TLM (Yes=1,No=2)
7. Was group work happening in the class on the day of your visit? (Yes=1,No=2)
8. Were children using square line book during math class? (Yes=1,No=2)
9. Are all the toilets in the school functional? (Yes=1,No=2)
10. Does the school have a separate functional toilet for girls? (Yes=1,No=2)
11. Does the school have drinking water? (Yes=1,No=2)
12. Is a Mid Day Meal served in the school? (Yes=1,No=2)

List 1

Code	Chapter for class 4	Chapter for class 5
1	Area and perimeter of simple geometric shapes	5 digit numbers
2	Number concepts	Addition
3	Addition	Subtraction
4	Subtraction	Multiples and factors
5	Multiplication 	Fractions
6	Division	Angles
7	Circles	Circles
8	Mental Maths	Length
9	Fractions	Area and perimeter
10	Money - Addition and Subtraction	Data
11	Measurement - Length	Multiplication 
12	Measurement - Weight	Division
13	Measurement - Volume	Mental Maths
14	Time	Decimals fractions
15	Data Management	Money
16	Pattern and Symmetry	Weight and Volume
17	Tangram	Time
18	Solid shapes	Symmetrical objects
19	-	3D shapes
20	-	Pattern

List 2

Code	Name of the TLM
1	Square counters
2	Number line and clothes clips
3	Abacus
4	Base Ten Blocks
5	Place Value mat
6	Place Value strips
7	Fraction shapes
8	Fraction strips
9	Decimal set
10	Decimal Place value strips
11	Dice
12	Geo-Board
13	Protractor and angle measure
14	Clock
15	Weighing Balance
16	Geo-solids with nets
17	Play money and coins
18	Tangram
19	Maths Concept Cards

![screenshot 2015-05-25 16 47 29](https://cloud.githubusercontent.com/assets/1021034/7796528/c2c5c070-02fd-11e5-9b7f-069fc0a36ed7.png)

**Comment by gkjohn** [comment]
Kannada version

ಶಾಲೆ ತೆರೆದಿತ್ತೆ?
ನೀವು ಯಾವ ತರಗತಿ ನೋಡಿದಿರಿ? (ನಾಲ್ಕನೇ ತರಗತಿಗೆ 1 ಒತ್ತಿರಿ, ಐದನೇ ತರಗತಿಗೆ 2 ಒತ್ತಿರಿ)
ನೀವು ನೋಡಿದಾಗ ಗಣಿತ ಪಾಠ ನಡೆಯುತ್ತಿತ್ತೇ? ( ಹೌದು ಎಂದರೆ 1 ಒತ್ತಿರಿ, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
ಪಠ್ಯಪುಸ್ತಕದ ಎಷ್ಟನೇ ಪಾಠ ಹೇಳಿಕೊಡಲಾಗುತ್ತಿತ್ತು ? ( ದಯವಿಟ್ಟು ಪಾಠದ ಕೋಡ್ ನಮೂದಿಸಿ)
ಗಣಿತ ಕಲಿಕಾ ಆಂದೋಲನದ ಯಾವ ಪುಸ್ತಕಗಳನ್ನು ಶಿಕ್ಷಕರು ಉಪಯೋಗಿಸುತ್ತಿದ್ದರು? (ದಯವಿಟ್ಟು TLM ಕೋಡ್ ಒತ್ತಿರಿ)
ಮಕ್ಕಳು ಗಣಿತ ಕಲಿಕಾ ಆಂದೋಲನದ ಪುಸ್ತಕಗಳನ್ನು ಉಪಯೋಗಿಸುತ್ತಿದ್ದುದು ನೀವು ನೋಡಿದಿರಾ? ( ಹೌದು ಎಂದರೆ 1 ಒತ್ತಿರಿ, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
ನೀವು ಶಾಲೆಗೆ ಹೋದ ದಿನ ಗುಂಪು ಕಾರ್ಯಕ್ರಮಗಳು ನಡೆಯುತ್ತಿದ್ದವೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
ಮಕ್ಕಳು ಚದುರಗೆರೆಯ ಪುಸ್ತಕಗಳನ್ನು ಗಣಿತ ತರಗತಿಯಲ್ಲಿ ಉಪಯೋಗಿಸುತ್ತಿದ್ದರೆ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
ಶಾಲೆಯಲ್ಲಿನ ಎಲ್ಲಾ ಶೌಚಾಲಯಗಳು ಕಾರ್ಯ ನಿರ್ವಹಿಸುತ್ತಿದ್ದವೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
ಶಾಲೆಯಲ್ಲಿ ಹೆಣ್ಣು ಮಕ್ಕಳಿಗೆ ಕಾರ್ಯ ನಿರ್ವಹಿಸುವ ಪ್ರತ್ಯೇಕ ಶೌಚಾಲಯ ಇದೆಯೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
ಶಾಲೆಯಲ್ಲಿ ಕುಡಿಯುವ ನೀರು ಇದೆಯೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)
ಶಾಲೆಯಲ್ಲಿ ಮಧ್ಯಾನ ಭೋಜನ ಕೊಡಲಾಗುತ್ತಿದೆಯೇ? ( ಹೌದು ಎಂದರೆ 1, ಇಲ್ಲ ಎಂದರೆ 2 ಒತ್ತಿರಿ)

**Comment by vamsee** [comment]
I'm listing the full flow of questions/instructions in the GKA IVRS. Please feel free to edit them as you like, but also we need Kannada translation for these. 

**Welcome message**

1. Welcome to Akshara GKA IVR system. Please enter your School ID and press hash key to continue.
2. Was the school information correct? Please press 1 for yes, 2 for no.
3. Sorry, there seems to be a problem. Please try again or call back later.

**Question 1**

1. Was the school open? Please enter 1 for yes, 2 for no.
2. Sorry, that is an invalid input. Please try again.
3. Sorry, there seems to be a problem. Please try again or call back later. [Same as above]

**Question 2**

1. Please enter the class you have visited. Press 4 for fourth standard, and 5 for fifth standard.
2. Sorry, that is an invalid input. Please try again. [Same as above]
3. Sorry, there seems to be a problem. Please try again or call back later. [Same as above]

**Comment by harisibrahimkv** [comment]
@vamsee I've deployed the latest code (completed migrations and loaded fixtures) on dev. Following are the endpoints. If you have time, do put them wherever necessary in the Exotel flow. Otherwise I'll do that in a day.

- /api/v1/ivrs/check-school/
- /api/v1/ivrs/read-school/
- /api/v1/ivrs/verify/ (Only use this for question 4 & 5 and the opening School ID confirmations)
- /api/v1/ivrs/verify-answer/ (For all the answers except the above three. This includes the numbers from both the lists - Chapters and TLM codes)
- /api/v1/ivrs/read-chapter/
- /api/v1/ivrs/read-tlm/
- /api/v1/ivrs/hangup/

cc @batpad

**Comment by gkjohn** [comment]
Final TLM and Chapter Codes

Code Name of the TLM
1	Square counters
2	Number line and clothes clips
3	Abacus
4	Base Ten Blocks
5	Place Value mat
6	Place Value strips
7	Fraction shapes
8	Fraction strips
9	Decimal set
10	Decimal Place value strips
11	Dice
12	Geo-Board
13	Protractor and angle measure
14	Clock
15	Weighing Balance
16	Geo-solids with nets
17	Play money Coins
18	Coins
19	Tangram
20	Measuring Tape
21	Maths Concept Cards

Code	Chapter for class 4
1	Area and perimeter of simple geometric shapes
2	Number concepts
3	Addition
4	Subtraction
5	Multiplication 
6	Division
7	Circles
8	Mental Maths
9	Fractions
10	Money - Addition and Subtraction
11	Measurement - Length
12	Measurement - Weight
13	Measurement - Volume
14	Time
15	Data Management
16	Pattern and Symmetry
17	Tangram
18	Solid shapes
19	-
20	-

Code	Chapter for class 5
1	5 digit numbers
2	Addition
3	Subtraction
4	Multiples and factors
5	Fractions
6	Angles
7	Circles
8	Length
9	Area and perimeter
10	Data
11	Multiplication 
12	Division
13	Mental Maths
14	Decimals fractions
15	Money
16	Weight and Volume
17	Time
18	Symmetrical objects
19	3D shapes
20	Pattern

![screenshot 2015-07-15 18 09 05](https://cloud.githubusercontent.com/assets/1021034/8698534/be9ad6b0-2b1c-11e5-9353-925e4e4c4c55.png)
![screenshot 2015-07-15 18 08 58](https://cloud.githubusercontent.com/assets/1021034/8698535/bed9b704-2b1c-11e5-9105-1b120aed64b6.png)

@harisibrahimkv

**Comment by gkjohn** [comment]
Hi @harisibrahimkv and @vamsee. There is a change needed to this IVRS flow. The current one is too complex and long for users. 

**Welcome message**

1. Welcome to Akshara Ganitha Kalika Andolana IVR system. Please enter your School ID and press hash key to continue.
2. Was the school information correct? Please press 1 for yes, 2 for no.
3. Sorry, that is not a valid input. Please try again.
4. Sorry, there seems to be a problem. Please try again or call back later.
5. Sorry, we are not able to find any school with that I.D. Please try again.

**Question 1**

1. Was the school open? Please enter 1 for yes, 2 for no. [If no, end call with message.]

**Question 2** MODIFIED

1. Please enter the class you have visited. Press 4 for fourth standard, and 5 for fifth standard. If another class, please press 8.

**Question 3**

1. Was the math class happening on the day of your visit? Press 1 for yes, 2 for no. [If yes, ask question 4. If no, skip to question 5.]

**Question 4**

1. Did you see children using the Ganitha Kalika Andolana TLM? Press 1 for yes, 2 for no.

**Question 5**

1. Are all the toilets in the school functional? Press 1 for yes, 2 for no. 

**Question 6**

1. Does the school have a separate functional toilet for girls? Press 1 for yes, 2 for no.

**Question 7**

1. Does the school have drinking water? Press 1 for yes, 2 for no.

**Question 8**

1. Is a Mid Day Meal served in the school? Press 1 for yes, 2 for no.

**Goodbye message**

1. Your answers have been successfully saved. Thank you for your time. Goodbye.

**Comment by harisibrahimkv** [comment]
Implemented. Details here: https://github.com/klpdotorg/dubdubdub/blob/develop/apps/ivrs/INFO.txt#L40

**Comment by gkjohn** [comment]
Hi @harisibrahimkv and @vamsee. There is a change needed to this IVRS flow - let's call it GKA v3. @meghaklp   

***Welcome message***

1. Welcome to Akshara Ganitha Kalika Andolana IVR system. Please enter your School ID and press hash key to continue.
2. Was the school information correct? Please press 1 for yes, 2 for no.
3. Sorry, that is not a valid input. Please try again.
4. Sorry, there seems to be a problem. Please try again or call back later.
5. Sorry, we are not able to find any school with that I.D. Please try again.

***Question 1*** [Maps to Question 1 and 2 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929]

Please enter the class you have visited. Press 4 for fourth standard, and 5 for fifth standard. If the school was closed, press 0. [If closed, skip all further questions and play thank you message.]

***Question 2*** [New]

Was the teacher is trained in GKA methodology? Press 1 for yes, 2 for no.

***Question 3*** [Maps to Question 3 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929]

Did you observe the math class happening? Press 1 for yes, 2 for no. [If no, skip questions 4, 5 and 6 and go to question 7.]

***Question 4*** [Maps to Question 4 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929 and Question 5 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-119920642]

Which Ganitha Kalika Andolana TLM was being used during the class? Enter the TLM code you saw being used. If you did not see TLM being used, press 99. If you saw multiple TLM being used, press 55. [Validation required - valid TLM IDs are 1 - 21 only.]

***Question 5*** [New]

Did you see representational stage being practiced during the class? Press 1 for yes, 2 for no.

***Question 6*** [Maps to Question 7 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-119920642]

Did you see group work happening? Press 1 for yes, 2 for no.

***Question 7*** [Maps to Question 5 and 6 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929]

Does the school have separate functional toilets for girls? Press 1 for yes, 2 for no.

***Goodbye Message*** 

Your answers have been successfully saved. Thank you for your time. Goodbye.

**Comment by brijeshpoojary** [comment]
hi, 
Mentioned below is the kannada text for GKA ivrs v3 questions.

1. ನೀವು ಯಾವ ತರಗತಿಯನ್ನು ವೀಕ್ಷಿಸಿದಿರಿ, ಎಂಬುವುದನ್ನು ನಮೋದಿಸಿ. ಉದಾಹರಣೆಗೆ 1ನೇ ತರಗತಿಗೆ 1ನ್ನು ಒತ್ತಿರಿ, 2ನೇ ತರಗತಿಗೆ 2ನ್ನು ಒತ್ತಿರಿ. ಶಾಲೆ ತೆರೆಯದಿದಲ್ಲಿ 0ನ್ನು ಒತ್ತಿರಿ. 

2. ನೀವು ಭೇಟಿ ನೀಡಿದ ಶಾಲೆಯಲ್ಲಿ 4 ಮತ್ತು 5ನೇ ತರಗತಿಯ ಗಣಿತ ಶಿಕ್ಷಕರಿಗೆ ಗಣಿತ ಕಲಿಕಾ ಆಂದೋಲನದ ತರಬೇತಿಯಾಗಿದೆಯೇ? (ಹೌದು ಎಂದರೆ 1ನ್ನು ಒತ್ತಿರಿ, ಇಲ್ಲ ಎಂದರೆ 2ನ್ನು ಒತ್ತಿರಿ)  

3. ನೀವು ವೀಕ್ಷಿಸಿದ ತರಗತಿಯಲ್ಲಿ  ಗಣಿತದ  ಪಾಠ ನಡೆಯುತ್ತಿತ್ತೇ? (ಹೌದು ಎಂದರೆ 1ನ್ನು ಒತ್ತಿರಿ, ಇಲ್ಲ ಎಂದರೆ 2ನ್ನು ಒತ್ತಿರಿ)

4. ಗಣಿತ ತರಗತಿಯಲ್ಲಿ ಗಣಿತ ಕಲಿಕಾ ಆಂದೋಲನದ ಯಾವ ಕಲಿಕೋಪಕರಣವನ್ನು ಉಪಯೋಗಿಸುತ್ತಿದ್ದರು? (ದಯವಿಟ್ಟು ನೀವು ಗಮನಿಸಿದ ಕಲಿಕೋಪಕರಣದ ಕೋಡ್ನ್ನು ನಮೂದಿಸಿ, ಕಲಿಕೋಪಕರಣಗಳನ್ನು ಉಪಯೋಗಿಸದಿದ್ದಲ್ಲಿ 99 ಅನ್ನು ಒತ್ತಿರಿ ಒಂದಕ್ಕಿಂತ ಹಿಚ್ಚಿನ ಕಲಿಕೋಪಕರಣಗಳನ್ನು ಉಪಯೋಗಿಸುವುದು ಕಂಡುಬಂದಲ್ಲಿ 55 ಅನ್ನು ಒತ್ತಿರಿ).

5. ನೀವು ವೀಕ್ಷಿಸಿದ ಗಣಿತ ತರಗತಿಯಲ್ಲಿ ಪ್ರಾತಿನಿಧ್ಯಾತ್ಮಕ ಹಂತವನ್ನು ಅನುಸರಿಸುತ್ತಿರುವುದು ಕಂಡುಬಂತೇ? (ಹೌದು ಎಂದರೆ 1ನ್ನು ಒತ್ತಿರಿ, ಇಲ್ಲ ಎಂದರೆ 2ನ್ನು ಒತ್ತಿರಿ)

6. ನೀವು ಶಾಲೆಗೆ ಹೋದ ದಿನ ಗಣಿತ ತರಗತಿಯಲ್ಲಿ  ಮಕ್ಕಳು ಗುಂಪು ಚಟುವಟಿಕೆಯಲ್ಲಿ ನಿರತರಾಗಿದ್ದರೇ? (ಹೌದು ಎಂದರೆ 1ನ್ನು ಒತ್ತಿರಿ, ಇಲ್ಲ ಎಂದರೆ 2ನ್ನು ಒತ್ತಿರಿ).

7. ಶಾಲೆಯಲ್ಲಿ ಹೆಣ್ಣು ಮಕ್ಕಳಿಗೆ ಬಳಸಲು   ಯೋಗ್ಯವಾದ ಪ್ರತ್ಯೇಕ ಶೌಚಾಲಯ ಇದೆಯೇ? ( ಹೌದು ಎಂದರೆ 1ನ್ನು, ಇಲ್ಲ ಎಂದರೆ 2ನ್ನು ಒತ್ತಿರಿ)

**Comment by harisibrahimkv** [comment]
Implemented. Details here: https://github.com/klpdotorg/dubdubdub/blob/develop/apps/ivrs/README.md

**Comment by gkjohn** [comment]
Hi @harisibrahimkv and @vamsee. There is a small change needed to this IVRS flow - let's call it GKA v3.2 @meghaklp   

The change is in the first question. 

***Welcome message***

1. Welcome to Akshara Ganitha Kalika Andolana IVR system. Please enter your School ID and press hash key to continue.
2. Was the school information correct? Please press 1 for yes, 2 for no.
3. Sorry, that is not a valid input. Please try again.
4. Sorry, there seems to be a problem. Please try again or call back later.
5. Sorry, we are not able to find any school with that I.D. Please try again.

***Question 1 & 2*** [Maps to Question 1 and 2 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929]

Please enter the class you have visited. Press 4 for fourth standard, and 5 for fifth standard. If the school was closed press 0" [If closed, skip all further questions and play thank you message.]

***Question 3*** [New]

Were the class 4 and 5 math teachers trained in GKA methodology in the school you have visited? Press 1 for yes, 2 for no

***Question 4*** [Maps to Question 3 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929]

Did you observe the math class happening? Press 1 for yes, 2 for no. [If no, skip questions 5, 6, 7, 8, 9 and go to question 10.]

***Question 5 & 6 & 7*** [Maps to Question 4 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929 and Question 5 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-119920642]

Which Ganitha Kalika Andolana TLM was being used during the class? Enter the TLM code you saw being used. If you did not see TLM being used, press 99. If you saw multiple TLM being used, press 55. [Validation required - valid TLM IDs are 1 - 21 only.]

***Question 8*** [New]

Did you see representational stage being practiced during the class? Press 1 for yes, 2 for no.

***Question 9*** [Maps to Question 7 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-119920642]

Did you see group work happening? Press 1 for yes, 2 for no.

***Question 10*** [Maps to Question 5 and 6 from https://github.com/klpdotorg/dubdubdub/issues/549#issuecomment-148724929]

Does the school have separate functional toilets for girls? Press 1 for yes, 2 for no.

***Goodbye Message*** 

Your answers have been successfully saved. Thank you for your time. Goodbye.

**Comment by harisibrahimkv** [comment]
Implemented in https://github.com/klpdotorg/dubdubdub/pull/610
