### ISSUE TITLE
End-points required to support Exotel IVRS system

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#553]
@vamsee can you outline what are the end-points we would need here? My guess is one that accepts a school id and returns whether it is a> a school, b> a preschool or c> is invalid ? And then another one that accepts the incoming data from exotel and saves it into the db? Any others? Would you be able to outline a bit more for both as to what exactly is required / sample data formats, etc.? And then either I or @harisibrahimkv could work on writing those end-points into dubdubdub.

Thanks!

**Comment by harisibrahimkv** [comment]
Implemented.
