### ISSUE TITLE
Boundary-Pages

### ISSUE THREAD

**Issue by aksanoble** [klpdotorg/dubdubdub#584]
Let's discuss these over a call. 
- [x] Academic Year Filter to be implemented @aksanoble
- [x] 'Compare to' Button --> Moved to future release

Primary Schools
- [x] Better match for boundary for DISE API @batpad @iambibhas --> Implement and test. Handle exceptions separately. 
- [x] For categories such as model primary etc, data on klp not available whereas mockup shows comparison. --> @iambibhas to be included in the api 
- [x] Data source unclear for Languages and Enrollment. Right now due to alignment it seems that Languages is from KLP and Enrollment is from DISE. --> To add a divider and source to be added.  @meghaklp 
- [x] Do we have Enrollment data for Upper Prim and Lower Primary in KLP API? --> To be made available in the API. @iambibhas 
- [x] Do we have Mother Tongue data for Primary schools in the KLP API? @iambibhas 

Primary Schools > Infrastructure
- [x] Couldn't find All weather pucca buildings in the DISE API --> @iambibhas to check if the data point exists. 
- [x] Toilets and Computers : We have averages and sum of toilets / computers. The mockup shows percentage of schools having toilets / computers. Data insufficient. --> To be included in the API. @iambibhas 
- [x]  Grant Received versus Grant Expected? Also do we sum avg_tlm_grant_expnd avg_school_dev_grant_expnd under grants? --> Verify types of data and render @iambibhas 

Preschools
- [x] Do we have Infrastructure data available? --> Yes, needs to be worked on @harisibrahimkv 
- [x] Enrollment data API available? --> @iambibhas

**Comment by gkjohn** [comment]
@aksanoble Lemme know when the call is.

**Comment by meghaklp** [comment]
Let me know too @aksanoble 

I looked at the Boundary page again (after a really long time). That Language enrollment thing is confusing, yes. I'll fix it before we can speak - in the mock up at least.

**Comment by meghaklp** [comment]
So, i've fixed enrollment by category and distinguished mother tongue and medium of instruction as below. 
![boundarysschoolpage](https://cloud.githubusercontent.com/assets/465382/10425906/0783a6d2-70f9-11e5-965c-303f0f9a45d7.png)

**Comment by gkjohn** [comment]
The pre-school infrastructure is next on @harisibrahimkv's plate.

**Comment by meghaklp** [comment]
![boundarysschoolpagev2](https://cloud.githubusercontent.com/assets/465382/10431543/48855156-7123-11e5-9fdb-81b713f79fb5.png)
![boundaryspreschoolpagev2](https://cloud.githubusercontent.com/assets/465382/10431552/53a91838-7123-11e5-9673-18bfcf19b58d.png)

**Comment by meghaklp** [comment]
@aksanoble - Changes are on branch called boundary_page_mockup

**Comment by iambibhas** [comment]
That "All weather pucca building" data is missing on DISE. On the DCF, pucca only shows up for classroom conditions and boundary wall. And even for classroom condition, we dont have the data separately for pucca classrooms.

**Comment by iambibhas** [comment]
the grant numbers seem independent of classroom number

``` school_code | sch_category | tot_clrooms | school_dev_grant_recd | school_dev_grant_expnd 
-------------+--------------+-------------+-----------------------+------------------------
 29111415203 |            1 |           2 |                  5000 |                      0
 29011105601 |            2 |          10 |                 12000 |                  12000
 29020202101 |            1 |           5 |                  5000 |                   5000
 29020202912 |            1 |           5 |                     0 |                      0
 29020706901 |            2 |           7 |                 12000 |                  12000
 29030509203 |            1 |           3 |                     0 |                      0
 29040110402 |            1 |           3 |                  5000 |                   5000
 29040110809 |            1 |           3 |                     0 |                      0
 29010400601 |            2 |          10 |                 12000 |                  12000
 29070311365 |            1 |           5 |                     0 |                      0```

**Comment by meghaklp** [comment]
Can we check if
1) The DCF has different logic for financial grant allocation
2) This School Development Grant maybe the same as Maintenance grant. Maybe they aren't reporting school Grant. @gkjohn is there a way to figure if these grants have been revised?
3)Maybe we leave category out and see:
How many schools with > 3 classrooms report a grant < 10000
This is received & spent grant in DISE as against expected grant which is based on the formula.

**Comment by meghaklp** [comment]
@iambibhas ^

**Comment by meghaklp** [comment]
@iambibhas What are the options for building? We should be asking maybe -
how many schools are in the best possible building they can be in?
