### ISSUE TITLE
Fixes for GKA SMS report generation script.

### ISSUE THREAD

**Issue by harisibrahimkv** [klpdotorg/dubdubdub#637]
- [x] Remove raising APIExceptions

- [x] Dynamically generate the list of district ids.

- [x] Make `date` args mandatory or fall back to default `dates`

- [x] Confirm whether we require `is_featured=True`. We might need to omit that filter since these questions necessarily need not be featured (returned in the stories endpoints).

**Comment by meghaklp** [comment]
@harisibrahimkv how do we dynamically generate the list of ids? You could reverse engineer fro the SMS - Story-schoolids but, isn't that efficient, no?

I'll remove is_featured.

**Comment by harisibrahimkv** [comment]
Fixed.
