### ISSUE TITLE
Data Source

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#672]
It appears that the only way to identify the source of data is in the footer. Is it possible to make that feature in the header so the source is apparent at first glance?

**Comment by meghaklp** [comment]
![image](https://cloud.githubusercontent.com/assets/465382/24794521/a025a826-1ba3-11e7-9586-530242614888.png)
![image](https://cloud.githubusercontent.com/assets/465382/24794551/b26600ee-1ba3-11e7-9568-3e5e714aadd0.png)
