### ISSUE TITLE
Colour code PTR 

### ISSUE THREAD

**Issue by gkjohn** [klpdotorg/dubdubdub#673]
Maybe colour code the PTR number if higher or lower than expected value? 

![screenshot 2017-03-29 09 49 29](https://cloud.githubusercontent.com/assets/1021034/24438448/2653cedc-1465-11e7-8b28-2921ee8c1f41.png)

**Comment by meghaklp** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/465382/24800692/c7dad786-1bbe-11e7-8d92-d38d868fb77d.png)
