### ISSUE TITLE
Finance - Expected grant section

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/dubdubdub#676]
This part of the boy girl distribution doesn't add up to the expected grant number above it:

![image](https://cloud.githubusercontent.com/assets/465382/24709478/ad87ce30-1a37-11e7-81d5-4b1da017294f.png)

**Comment by meghaklp** [comment]
Looks like the number in pink and blue is actually the count of students. whereas the expected grant has to be divided in that ratio. I can see if it's a front end issue.

**Comment by shivangi** [comment]
I have not calculated the amount per gender per student. Javascript is just sending number of girls and boys (not their financial division)

**Comment by meghaklp** [comment]
Fixed.
![image](https://cloud.githubusercontent.com/assets/465382/24801327/5f80e75e-1bc1-11e7-947a-40c1341c3a29.png)
