### ISSUE TITLE
KLP Demographics Report - Mother tongue

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/dubdubdub#677]
@shivangi - now the mother tongue break up does not add up to the total student count

**Comment by shivangi** [comment]
Ok, so i was just looking at these counts and its different number as for getting this even Model Primary type is being used. 
Also though the school is of type Upper or Lower it has students in class 9! :(
So once db clean up happens the class 9 students should disappear.
But what to do about Model Primary? Should we consider them?

**Comment by meghaklp** [comment]
Actually model primaries are upper primaries. They just get some special
credits for being "model" well run schools.

**Comment by shivangi** [comment]
OK, so should i add them to Upper Primary?

**Comment by meghaklp** [comment]
Yes.

**Comment by shivangi** [comment]
Done
